spring:
  application:
    name: feign

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
# 通用配置
ribbon:
  MaxAutoRetries: 1

# 针对指定服务生效的配置
item-service:
  ribbon:
    MaxAutoRetries: 0

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
